### ISSUE TITLE
All walls appear as blank textures on map edits

### ISSUE THREAD

**Issue by EuSouAFazer** [wall-nerds/wallening#247] opened 2024-06-28 16:18 UTC
![image](https://github.com/wall-nerds/wallening/assets/84548101/7909785f-3d89-40b2-adb3-428d24e6c3c3)

Open shutters also have this same problem as well.

**Comment by unit0016** [comment] 2024-06-28 22:13
dupe of https://github.com/wall-nerds/wallening/issues/122

**Closed as completed** 2024-08-01 06:39 UTC
Labels: Mapping, Design, Code (Structure)
