### ISSUE TITLE
Massive grey blob shows up in Multi-Z

### ISSUE THREAD

**Issue by Imaginos16** [wall-nerds/wallening#25] opened 2022-05-08 02:38 UTC
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Run IceBox
Go to the chapel area with the big clearing to the lower level
See this:
![image](https://user-images.githubusercontent.com/77556824/167279405-be8ec446-ca9d-4b56-86b7-736717641946.png)

**Comment by LemonInTheDark** [comment] 2022-05-08 02:45
Mutliz is just straight up not supported atm because of how our vis contents handles planes.
That said, this is not the expected behavior even given that.

**Comment by PKPenguin321** [comment] 2022-05-08 03:30
Can confirm this is a pretty bad and very blatant issue
![image](https://user-images.githubusercontent.com/8345184/167280538-83408965-8621-4ee9-9499-cedda24a2b53.png)
![image](https://user-images.githubusercontent.com/8345184/167280541-9ba4b9bd-84ce-4ad7-8ac1-4c86b958dc7d.png)
![image](https://user-images.githubusercontent.com/8345184/167280545-ea20ff08-6d58-4c38-a902-8a443df514b4.png)

**Comment by LemonInTheDark** [comment] 2022-05-08 03:39
Bets are this has to do with how the map loaded or something. will non the less look into it tho

**Comment by tralezab** [comment] 2022-09-30 23:32
fixed by potato!

**Closed as completed by tralezab** 2022-09-30 23:32 UTC
Labels: Code (Visual), Merge issue
