### ISSUE TITLE
Wheelchairs are offset incorrectly.

### ISSUE THREAD

**Issue by dalmationer** [wall-nerds/wallening#278] opened 2024-08-02 20:25 UTC
the offset on wheelchairs is currently not inline with the offset on players, making it appear that players are floating or standing above the wheelchair.

reproduction:

buckle your character to a wheelchair.

**Comment by ArcaneMusic** [comment] 2024-08-03 01:29
Dupe of #268, fun fact that wheelchairs are *technically* vehicles!

**Closed as completed** 2024-08-04 11:49 UTC
