### ISSUE TITLE
Ghost mask moves with animation, causing a transparent strip

### ISSUE THREAD

**Issue by dragomagol** [wall-nerds/wallening#4] opened 2022-05-08 00:46 UTC
![image](https://user-images.githubusercontent.com/66640614/167276964-b4e3bf47-088f-447b-9b7a-81f3d20bf66d.png)

**Comment by dragomagol** [comment] 2022-05-08 00:49
![image](https://user-images.githubusercontent.com/66640614/167277023-2d712e1a-9bf8-4dcb-a846-3918c400ea1a.png)

**Comment by dragomagol** [comment] 2022-05-08 00:49
![image](https://user-images.githubusercontent.com/66640614/167277028-acad7dd5-097a-4227-b0c6-40f676e18015.png)

**Comment by LemonInTheDark** [comment] 2022-05-08 00:55
dupe of https://github.com/wall-nerds/wallening/issues/3

**Closed as completed** 2022-05-08 01:16 UTC

**Comment by PKPenguin321** [comment] 2022-05-08 03:47
Not sure that it's a proper dupe, as the other issue doesn't take into account the animation. The harsh edge bobs up and down with the ghost as it moves idly.
